# Generated by Django 4.0.6 on 2022-09-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0002_alter_conta_tel_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='conta',
            field=models.CharField(max_length=30, verbose_name='Nome da Conta'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='pix',
            field=models.CharField(blank=True, max_length=30, verbose_name='Chave PIX'),
        ),
    ]
