# Generated by Django 4.0.6 on 2022-10-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0003_alter_conta_conta_alter_conta_pix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Saldo'),
        ),
    ]
