# Generated by Django 4.0.6 on 2023-01-19 22:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Banco/Refência')),
                ('agencia', models.CharField(max_length=30, verbose_name='Agência')),
                ('conta', models.CharField(max_length=30, verbose_name='Conta')),
                ('saldo_dia', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=9, verbose_name='Saldo Inicial R$')),
                ('pix', models.CharField(blank=True, max_length=30, verbose_name='Chave PIX')),
                ('tel_contato', models.CharField(blank=True, max_length=11, unique=True, verbose_name='Telefone Contato')),
                ('logradouro', models.CharField(blank=True, max_length=200, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=5, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('cep', models.CharField(blank=True, max_length=11, verbose_name='CEP')),
                ('estado', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], max_length=2, verbose_name='Estado')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='CaixaDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('([A-Z])\\w+', 'Somente letras maiúsculas.')], verbose_name='Banco/Refência')),
                ('agencia', models.CharField(max_length=30, verbose_name='Agência')),
                ('conta', models.CharField(max_length=30, verbose_name='Conta')),
                ('saldo_dia', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True, verbose_name='Saldo Inicial R$')),
                ('pix', models.CharField(blank=True, max_length=30, verbose_name='Chave PIX')),
                ('tel_contato', models.CharField(blank=True, max_length=11, unique=True, verbose_name='Telefone Contato')),
                ('logradouro', models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator('([A-Z])\\w+', 'Somente letras maiúsculas.')], verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=5, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('cep', models.CharField(blank=True, max_length=11, verbose_name='CEP')),
                ('estado', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], max_length=2, verbose_name='Estado')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Caixa',
                'verbose_name_plural': 'Caixa',
            },
        ),
    ]
