# Generated by Django 4.0.6 on 2022-07-21 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banco',
            name='pix',
        ),
        migrations.AddField(
            model_name='banco',
            name='forma_pgto',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='Forma de Pagamento'),
            preserve_default=False,
        ),
    ]
