# Generated by Django 4.0.6 on 2022-07-21 21:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0002_remove_banco_pix_banco_forma_pgto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banco',
            name='forma_pgto',
        ),
        migrations.AddField(
            model_name='banco',
            name='pix',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='PIX'),
            preserve_default=False,
        ),
    ]
