# Generated by Django 4.0.6 on 2022-07-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0003_remove_banco_forma_pgto_banco_pix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='numero',
            field=models.CharField(max_length=5, verbose_name='Número'),
        ),
    ]
