# Generated by Django 4.0.6 on 2022-07-25 12:19

from django.db import migrations, models
import django.db.models.deletion
import django_cpf_cnpj.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fornecedor', models.CharField(max_length=200, verbose_name='Nome Fornecedor')),
                ('nome_contato', models.CharField(max_length=200, verbose_name='Nome Contato')),
                ('tel_principal', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Telefone Principal')),
                ('tel_contato', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Telefone Contato')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('cnpj', django_cpf_cnpj.fields.CNPJField(max_length=18)),
                ('insc_estadual', models.CharField(max_length=15, unique=True, verbose_name='Inscrição Estadual')),
                ('logradouro', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=30, verbose_name='Número')),
                ('complemento', models.CharField(max_length=100, null=True, verbose_name='Complemento')),
                ('cep', models.CharField(max_length=11, verbose_name='CEP')),
                ('estado', models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], max_length=2, verbose_name='Estado')),
                ('cidade', models.CharField(max_length=100, null=True, verbose_name='Cidade')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='banco.banco', verbose_name='Banco')),
            ],
        ),
    ]
