# Generated by Django 4.0.6 on 2022-08-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('descricao',),
            },
        ),
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'ordering': ['nome'], 'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.RenameField(
            model_name='fornecedor',
            old_name='nome_contato',
            new_name='contato',
        ),
        migrations.RenameField(
            model_name='fornecedor',
            old_name='nome_fornecedor',
            new_name='nome',
        ),
    ]
