# Generated by Django 4.0.6 on 2022-10-25 22:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='tel_contato',
            field=models.CharField(blank=True, max_length=11, unique=True, verbose_name='Telefone Contato'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='tel_principal',
            field=models.CharField(blank=True, max_length=11, unique=True, verbose_name='Telefone Principal'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cidade',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=100, verbose_name='Cidade'),
            preserve_default=False,
        ),
    ]
