# Generated by Django 4.0.6 on 2022-09-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0003_rename_historico_historicofornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='contato',
            field=models.CharField(max_length=200, verbose_name='Nome do Contato'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Fornecedor'),
        ),
    ]
