# Generated by Django 4.0.6 on 2022-07-25 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='num_venda',
        ),
    ]
