# Generated by Django 4.0.6 on 2022-10-25 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nome_cliente',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nome_contato',
            new_name='contato',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='data_venda',
            new_name='data',
        ),
    ]
