# Generated by Django 4.0.6 on 2022-07-21 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='responsavel',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Responsável da Obra'),
            preserve_default=False,
        ),
    ]
