# Generated by Django 4.0.6 on 2023-01-19 22:27

from django.db import migrations, models
import django.db.models.deletion
import produto.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Categoria')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Produto')),
                ('codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('ncm', models.CharField(max_length=10, validators=[produto.models.validate_campos], verbose_name='NCM')),
                ('cst', models.CharField(max_length=3, validators=[produto.models.validate_campos], verbose_name='CST')),
                ('cfop', models.CharField(max_length=4, validators=[produto.models.validate_campos], verbose_name='CFOP')),
                ('peso_barra', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Peso Barra')),
                ('estoque_ini', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Estoque Inicial')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('status_disponivel', models.BooleanField(default=True, verbose_name='Disponível')),
                ('criadoem', models.DateTimeField(auto_now_add=True)),
                ('atualizadoem', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produto.categoria', verbose_name='Categoria')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fornecedor.fornecedor')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(max_length=10, verbose_name='Un')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Unidade de Medida',
                'verbose_name_plural': 'Unidades de Medida',
            },
        ),
        migrations.CreateModel(
            name='Tributos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Valor unitário R$')),
                ('valor_barra_un', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Valor Barra/un R$')),
                ('taxa_icms_interno', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='ICMS INTERNO')),
                ('taxa_icms_inter', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='ICMS INTER')),
                ('icms_interno', models.DecimalField(decimal_places=4, default=0.0, max_digits=6, verbose_name='ICMS INTERNO')),
                ('icms_inter', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='ICMS INTER')),
                ('ali_dif_icms', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='AL ICMS')),
                ('dif_aliq_icms', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='DIF AL ICMS')),
                ('taxa_ipi', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='IPI')),
                ('ipi', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='IPI')),
                ('taxa_frete', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Taxa do Frete')),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Frete R$')),
                ('frete', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='FRETE')),
                ('base_icms_st', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='BASE CALCULO ICMS INTER ST')),
                ('base_calc_st', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='BASE CALCULO ST')),
                ('st', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='ST')),
                ('custo_final', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='CUSTO FINAL DA BARRA')),
                ('custo_frac', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='CUSTO FRACIONADO - ml')),
                ('preco_frac', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='PREÇO DE VENDA fracionada -ml')),
                ('mva', models.DecimalField(decimal_places=4, default=0.0, max_digits=6, verbose_name='MVA')),
                ('criadoem', models.DateTimeField(auto_now_add=True)),
                ('atualizadoem', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto')),
            ],
            options={
                'verbose_name': 'Tributo',
                'verbose_name_plural': 'Tributos',
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='unimed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produto.unidademedida', verbose_name='Unidade'),
        ),
    ]
