# Generated by Django 4.0.6 on 2022-10-26 11:25

from django.db import migrations, models
import produto.models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='disponivel',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='icms_1',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='icms_2',
        ),
        migrations.AddField(
            model_name='produto',
            name='aliquota_1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, verbose_name='Aliquota Interno 1'),
        ),
        migrations.AddField(
            model_name='produto',
            name='aliquota_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, verbose_name='Aliquota Interno 2'),
        ),
        migrations.AddField(
            model_name='produto',
            name='taxa_frete',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=5, verbose_name='Taxa Frete'),
        ),
        migrations.AddField(
            model_name='produto',
            name='valor_frete',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, verbose_name='valor para frete R$'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='cfop',
            field=models.CharField(blank=True, max_length=4, validators=[produto.models.validate_campos], verbose_name='CFOP'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='cst',
            field=models.CharField(blank=True, max_length=3, validators=[produto.models.validate_campos], verbose_name='CST'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ipi',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, verbose_name='IPI'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='mva',
            field=models.CharField(blank=True, max_length=3, validators=[produto.models.validate_campos], verbose_name='MVA'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ncm',
            field=models.CharField(blank=True, max_length=10, validators=[produto.models.validate_campos], verbose_name='NCM'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='peso_barra',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, verbose_name='Peso Barra'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, verbose_name='Quantidade de Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor_custo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Valor de Custo R$'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor_venda',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='valor de Venda R$'),
        ),
    ]
