# Generated by Django 4.0.6 on 2022-09-20 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='icms_1',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='icms_2',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='ipi',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='valor',
        ),
    ]
