# Generated by Django 4.0.6 on 2022-09-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_remove_produto_icms_1_remove_produto_icms_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='valor de Venda'),
        ),
        migrations.AddField(
            model_name='produto',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Valor de Custo'),
        ),
    ]
