# Generated by Django 4.1.1 on 2022-10-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_produto_valor_frete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='aliquota_1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, verbose_name='Aliquota Interno 1'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='aliquota_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, verbose_name='Aliquota Interno 2'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='taxa_frete',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=5, verbose_name='Taxa Frete'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor_frete',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, verbose_name='valor para frete R$'),
        ),
    ]
