# Generated by Django 4.0.6 on 2022-10-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_remove_produto_taxa_frete_remove_produto_valor_custo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='custo',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='frete',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='venda',
        ),
        migrations.AddField(
            model_name='produto',
            name='taxa_frete',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=5, verbose_name='Taxa Frete'),
        ),
        migrations.AddField(
            model_name='produto',
            name='valor_custo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Valor de Custo R$'),
        ),
        migrations.AddField(
            model_name='produto',
            name='valor_frete',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, verbose_name='valor para frete R$'),
        ),
        migrations.AddField(
            model_name='produto',
            name='valor_venda',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='valor de Venda R$'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='aliquota_1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, verbose_name='Aliquota Interno 1'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='aliquota_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, verbose_name='Aliquota Interno 2'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='peso_barra',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, verbose_name='Peso Barra'),
        ),
    ]
