# Generated by Django 4.0.6 on 2022-10-27 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_remove_produto_custo_remove_produto_frete_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidademedida',
            options={'verbose_name': 'Unidade de Medida', 'verbose_name_plural': 'Unidades de Medidas'},
        ),
    ]
