# Generated by Django 4.0.6 on 2022-10-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_alter_unidademedida_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='valor_custo',
        ),
        migrations.AddField(
            model_name='produto',
            name='custo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Valor de Custo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor_frete',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, verbose_name='valor para frete'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor_venda',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='valor de Venda'),
        ),
    ]
