# Generated by Django 4.0.6 on 2022-10-27 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_remove_produto_valor_custo_produto_custo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='valor_venda',
            new_name='venda',
        ),
    ]
