# Generated by Django 4.0.6 on 2022-10-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_rename_valor_venda_produto_venda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='valor_frete',
            new_name='frete',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='taxa_frete',
        ),
        migrations.AddField(
            model_name='produto',
            name='tfrete',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=5, verbose_name='Taxa de Frete'),
        ),
    ]
