# Generated by Django 4.0.6 on 2022-10-21 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compraproduto',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='vendaproduto',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.RenameField(
            model_name='compra',
            old_name='formapgto',
            new_name='formapgto_compra',
        ),
        migrations.RenameField(
            model_name='compra',
            old_name='imagem',
            new_name='imagem_compra',
        ),
        migrations.RenameField(
            model_name='compraproduto',
            old_name='compra',
            new_name='compra_produto',
        ),
        migrations.RenameField(
            model_name='compraproduto',
            old_name='quantidade',
            new_name='quant_produto_compra',
        ),
        migrations.RenameField(
            model_name='venda',
            old_name='formapgto',
            new_name='formapgto_venda',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='data',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='pgto_avista',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='total',
        ),
        migrations.RemoveField(
            model_name='compraproduto',
            name='detalhes',
        ),
        migrations.RemoveField(
            model_name='compraproduto',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='custo',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='data',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='num_venda',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='pgto_avista',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='total',
        ),
        migrations.RemoveField(
            model_name='vendaproduto',
            name='detalhes',
        ),
        migrations.RemoveField(
            model_name='vendaproduto',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='vendaproduto',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='vendaproduto',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='compra',
            name='codigo_compra',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, verbose_name='Código Compra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='data_compra',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data Compra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='total_compra',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True, verbose_name='Custo da Compra R$'),
        ),
        migrations.AddField(
            model_name='compraproduto',
            name='detalhes_compra',
            field=models.CharField(blank=True, max_length=300, verbose_name='Detalhes da Compra'),
        ),
        migrations.AddField(
            model_name='compraproduto',
            name='preco_compra_produto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Preço de Compra R$'),
        ),
        migrations.AddField(
            model_name='venda',
            name='codigo_venda',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, verbose_name='Código da Venda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='custo_venda',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Custo da venda R$'),
        ),
        migrations.AddField(
            model_name='venda',
            name='data_venda',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data Venda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='detalhes_venda',
            field=models.CharField(blank=True, max_length=300, verbose_name='Detalhes da Venda'),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='preco_venda_produto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Preço de Venda R$'),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='quant_produto_venda',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='status',
            field=models.CharField(choices=[('Pendente', 'pendente'), ('Aguardando', 'aguardando'), ('Entregue', 'entregue'), ('Cancelado', 'cancelado')], default='pendente', max_length=10, verbose_name='Condição'),
        ),
        migrations.AlterField(
            model_name='compraproduto',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal R$'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('Pendente', 'pendente'), ('Aguardando', 'aguardando'), ('Entregue', 'entregue'), ('Cancelado', 'cancelado')], default='pendente', max_length=10, verbose_name='Condição'),
        ),
    ]
