# Generated by Django 4.0.6 on 2022-10-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='data_venda',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='venda',
            old_name='custo',
            new_name='total',
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, default=5, max_digits=10, null=True, verbose_name='Preço de Venda'),
        ),
    ]
