# Generated by Django 4.0.6 on 2022-08-25 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financeiro', '0001_initial'),
        ('produto', '0001_initial'),
        ('cliente', '0001_initial'),
        ('fornecedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendaproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produto.produto', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.venda'),
        ),
        migrations.AddField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.cliente'),
        ),
        migrations.AddField(
            model_name='compraproduto',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.compra'),
        ),
        migrations.AddField(
            model_name='compraproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produto.produto', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='compra',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fornecedor.fornecedor'),
        ),
    ]
