# Generated by Django 4.0.6 on 2022-08-25 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0002_historico_alter_fornecedor_options_and_more'),
        ('financeiro', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('operacao', models.CharField(blank=True, choices=[('d', 'Debito'), ('c', 'Credito')], default='d', max_length=1)),
                ('status', models.CharField(blank=True, choices=[('a', 'A Pagar'), ('p', 'Pago')], default='a', max_length=1)),
                ('descricao', models.TextField(blank=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedor.fornecedor')),
                ('historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedor.historico')),
            ],
            options={
                'ordering': ('-data_vencimento', 'valor'),
            },
        ),
    ]
