# Generated by Django 4.0.6 on 2022-10-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_rename_data_venda_venda_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendaproduto',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal'),
        ),
    ]
