# Generated by Django 4.0.6 on 2022-07-27 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_compra_total_venda_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compraproduto',
            old_name='preço',
            new_name='preco',
        ),
        migrations.RenameField(
            model_name='vendaproduto',
            old_name='preço',
            new_name='preco',
        ),
    ]
