# Generated by Django 4.0.6 on 2022-10-25 21:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_vendaproduto_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='data_compra',
        ),
        migrations.AddField(
            model_name='compra',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data da Compra'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compra',
            name='codigo',
            field=models.CharField(max_length=10, verbose_name='Código da Compra'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='formapgto',
            field=models.CharField(choices=[('Pix', 'pix'), ('Cartão', 'cartão'), ('Dinheiro', 'dinheiro')], max_length=11, verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True, verbose_name='Total da Compra'),
        ),
        migrations.AlterField(
            model_name='compraprestacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor da Parcela'),
        ),
        migrations.AlterField(
            model_name='compraproduto',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Preço do Produto'),
        ),
        migrations.AlterField(
            model_name='compraproduto',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data',
            field=models.DateField(verbose_name='Data da Venda'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='formapgto',
            field=models.CharField(choices=[('Pix', 'pix'), ('Cartão', 'cartão'), ('Dinheiro', 'dinheiro')], max_length=11, verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Total da Venda'),
        ),
        migrations.AlterField(
            model_name='vendaprestacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor da Parcela'),
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, default=5, max_digits=10, null=True, verbose_name='Valor Produto'),
        ),
    ]
