# Generated by Django 4.0.6 on 2022-08-26 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_prestacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prestacao',
        ),
    ]
