# Generated by Django 4.0.6 on 2022-09-20 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_delete_prestacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraPrestacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestacao', models.PositiveIntegerField(verbose_name='Prestação')),
                ('vencimento', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Vencimento')),
                ('pago', models.BooleanField(verbose_name='Pago')),
                ('pagamento', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Pagamento')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.compra')),
            ],
        ),
    ]
