# Generated by Django 4.0.6 on 2022-09-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_compraprestacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='status',
            field=models.CharField(choices=[('Pendente', 'pendente'), ('Aguardando', 'aguardando'), ('Entregue', 'entregue'), ('Cancelado', 'cancelado')], default='pendente', max_length=10, verbose_name='Condição da entrega'),
        ),
        migrations.AlterField(
            model_name='compraprestacao',
            name='prestacao',
            field=models.CharField(max_length=5, verbose_name='Prestação'),
        ),
    ]
