# Generated by Django 4.0.6 on 2022-09-20 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_alter_compra_status_alter_compraprestacao_prestacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraprestacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='compraprestacao',
            name='pagamento',
            field=models.DateField(verbose_name='Pagamento'),
        ),
        migrations.AlterField(
            model_name='compraprestacao',
            name='prestacao',
            field=models.CharField(max_length=5, verbose_name='Parcela'),
        ),
        migrations.AlterField(
            model_name='compraprestacao',
            name='vencimento',
            field=models.DateField(verbose_name='Vencimento'),
        ),
        migrations.CreateModel(
            name='VendaPrestacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestacao', models.CharField(max_length=5, verbose_name='Parcela')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor')),
                ('vencimento', models.DateField(verbose_name='Vencimento')),
                ('pago', models.BooleanField(verbose_name='Pago')),
                ('pagamento', models.DateField(verbose_name='Pagamento')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.venda')),
            ],
        ),
    ]
