# Generated by Django 4.0.6 on 2022-09-20 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_compraprestacao_valor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compraprestacao',
            name='pago',
        ),
        migrations.RemoveField(
            model_name='vendaprestacao',
            name='pago',
        ),
    ]
