# Generated by Django 4.0.6 on 2022-09-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_remove_compraprestacao_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='pgto_avista',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True, verbose_name='Valor a vista'),
        ),
        migrations.AddField(
            model_name='venda',
            name='pgto_avista',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True, verbose_name='Valor a vista'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('Pendente', 'pendente'), ('Aguardando', 'aguardando'), ('Entregue', 'entregue'), ('Cancelado', 'cancelado')], default='pendente', max_length=10, verbose_name='Condição da entrega'),
        ),
    ]
