# Generated by Django 4.0.6 on 2022-09-28 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0009_compra_pgto_avista_venda_pgto_avista_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compraprestacao',
            options={'verbose_name': 'Prestação', 'verbose_name_plural': 'Prestações'},
        ),
        migrations.AlterModelOptions(
            name='vendaprestacao',
            options={'verbose_name': 'Prestação', 'verbose_name_plural': 'Prestações'},
        ),
    ]
