# Generated by Django 4.0.6 on 2022-10-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0010_alter_compraprestacao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='nfs_compras'),
        ),
    ]
