# Generated by Django 4.0.6 on 2022-10-25 22:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filho',
            old_name='nome_filho',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='data_admissao',
            new_name='admissao',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='nome_conjuge',
            new_name='conjuge',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='nome_empresa',
            new_name='empresa',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='estado_civil',
            new_name='est_civil',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='nome_mae',
            new_name='mae',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='data_nascimento',
            new_name='nascimento',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='nome_funcionario',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='nome_pai',
            new_name='pai',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='raca_cor',
            new_name='raca',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='tel_residencial',
            new_name='residencial',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='titulo_eleitor',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='vale_transporte',
            new_name='vtransporte',
        ),
        migrations.RemoveField(
            model_name='filho',
            name='data_nasc_filho',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='tel_celular',
        ),
        migrations.AddField(
            model_name='filho',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Nascimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='celular',
            field=models.CharField(blank=True, max_length=11, unique=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_rg',
            field=models.DateField(verbose_name='Data de Expedição'),
        ),
    ]
