# Generated by Django 4.0.6 on 2022-09-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='tel_celular',
            field=models.CharField(blank=True, max_length=11, unique=True, verbose_name='Telefone Celular'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='tel_residencial',
            field=models.CharField(blank=True, max_length=11, unique=True, verbose_name='Telefone Residencial'),
        ),
    ]
