# Generated by Django 4.0.6 on 2022-07-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(verbose_name='Data Admissão'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_nasc_filho',
            field=models.DateField(verbose_name='Data de Nascimento do Filho'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_rg',
            field=models.DateField(verbose_name='Data Expedição'),
        ),
    ]
