# Generated by Django 4.0.6 on 2022-10-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0002_rename_nome_filho_filho_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='admissao',
            field=models.DateField(verbose_name='Data de Admissão'),
        ),
    ]
