# Generated by Django 4.0.6 on 2022-09-28 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimento',
            options={'ordering': ['-created_at'], 'verbose_name': 'Movimentação de Estoque', 'verbose_name_plural': 'Movimentação de Estoque'},
        ),
        migrations.RemoveField(
            model_name='produtomovimento',
            name='preço',
        ),
        migrations.RemoveField(
            model_name='produtomovimento',
            name='subtotal',
        ),
    ]
