# Generated by Django 4.0.6 on 2022-07-25 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimento', '0002_alter_movimento_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='movimento',
        ),
        migrations.AlterModelOptions(
            name='movimento',
            options={'ordering': ['-created_at'], 'verbose_name': 'Movimento', 'verbose_name_plural': 'Movimento'},
        ),
        migrations.RemoveField(
            model_name='movimento',
            name='formapgto',
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
