# Generated by Django 4.0.6 on 2022-09-28 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimento', '0002_alter_movimento_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimento',
            name='total',
        ),
    ]
