# Generated by Django 4.0.6 on 2022-09-28 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movimento', '0003_remove_movimento_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimento',
            name='local',
            field=models.CharField(default=django.utils.timezone.now, max_length=6, verbose_name='Local'),
            preserve_default=False,
        ),
    ]
