# Generated by Django 4.0.6 on 2022-12-29 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateField(verbose_name='Data da Venda')),
                ('codigo', models.CharField(max_length=8, verbose_name='Número da Venda')),
                ('nota_fs', models.CharField(blank=True, max_length=10, verbose_name='Nota Fiscal')),
                ('custo_total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Valor da Venda')),
                ('desconto_venda', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Desconto %')),
                ('status_venda', models.CharField(choices=[('Pendente', 'pendente'), ('Aguardando', 'aguardando'), ('Entregue', 'entregue'), ('Cancelado', 'cancelado')], default='pendente', max_length=10, verbose_name='Condição')),
                ('num_parcelas', models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Parcelas')),
                ('vlr_parcelas', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor parcelas')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas - Contas a Receber',
            },
        ),
        migrations.CreateModel(
            name='VendaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=255, verbose_name='Produto')),
                ('quantidade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantidade')),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor de Venda')),
                ('detalhes', models.CharField(blank=True, max_length=300, verbose_name='Detalhes da Venda')),
                ('status', models.CharField(choices=[('Pendente', 'pendente'), ('Aguardando', 'aguardando'), ('Entregue', 'entregue'), ('Cancelado', 'cancelado')], default='pendente', max_length=10, verbose_name='Condição')),
                ('custo_venda', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Subtotal')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venda.venda')),
            ],
            options={
                'verbose_name': 'Produto da Venda',
                'verbose_name_plural': 'Produtos da Venda',
            },
        ),
        migrations.CreateModel(
            name='VendaPrestacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_parcela', models.IntegerField(blank=True, null=True, verbose_name='Número da Parcela')),
                ('valor_parc', models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Valor das Parcelas R$')),
                ('formapgto', models.CharField(blank=True, choices=[('Boleto', 'Boleto'), ('Cheque', 'Cheque'), ('C/Entrega', 'C/Entrega'), ('Pix', 'Pix'), ('Cartão', 'Cartão'), ('Dinheiro', 'Dinheiro')], max_length=11, null=True, verbose_name='Forma pgto')),
                ('data_venc', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pgto', models.DateField(verbose_name='Data de Pagamento')),
                ('detalhes', models.CharField(blank=True, max_length=300, verbose_name='Detalhes da Prestação')),
                ('status', models.BooleanField(default=False, verbose_name='Quitado')),
                ('banco', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='banco.caixadia')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venda.venda')),
            ],
            options={
                'verbose_name': 'Parcela da Venda',
                'verbose_name_plural': 'Prestações da Venda',
            },
        ),
    ]
