# Generated by Django 4.0.6 on 2023-01-08 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_alter_tributos_produto'),
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendaprestacao',
            name='num_parcela',
            field=models.IntegerField(blank=True, default=0.0, null=True, verbose_name='Número da Parcela'),
        ),
        migrations.AlterField(
            model_name='vendaprestacao',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestacoes', to='venda.venda'),
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='venda.venda'),
        ),
    ]
